EXPERIMENT:
  NAME: ""
  TAG: "multidkd_,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MTDKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
  MULTITEACHER: True
  OTHERTEACHERS: ["ResNet50", "resnet56", "resnet110", "vgg13", "wrn_40_2"]
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

